// Code generated by go-swagger; DO NOT EDIT.

// Package server Tribe
//
//  This is a REST API reference for the Tribe Admin
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /v1
//  Version: v1alpha
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package server
