// Code generated by go-swagger; DO NOT EDIT.

package server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "swagger": "2.0",
  "info": {
    "description": "This is a REST API reference for the Tribe Admin",
    "title": "Tribe",
    "version": "v1alpha"
  },
  "basePath": "/v1",
  "paths": {
    "/-/healthy": {
      "get": {
        "description": "An endpoint which responds health checks\n",
        "tags": [
          "healthz"
        ],
        "summary": "Health check",
        "responses": {
          "200": {
            "description": "Success"
          },
          "503": {
            "description": "Service Unavailable",
            "schema": {
              "$ref": "#/definitions/Problem"
            }
          }
        }
      }
    },
    "/-/ready": {
      "get": {
        "description": "An endpoint which responds readiness checks. This probe is\ncalled to check whether the service is ready to receive traffic.\n",
        "tags": [
          "healthz"
        ],
        "summary": "Readiness check",
        "responses": {
          "200": {
            "description": "Success"
          },
          "503": {
            "description": "Service Unavailable",
            "schema": {
              "$ref": "#/definitions/Problem"
            }
          }
        }
      }
    },
    "/realms": {
      "get": {
        "tags": [
          "realms"
        ],
        "summary": "List realms",
        "operationId": "list-realms",
        "parameters": [
          {
            "$ref": "#/parameters/offset"
          },
          {
            "$ref": "#/parameters/limit"
          }
        ],
        "responses": {
          "200": {
            "description": "found",
            "schema": {
              "type": "object",
              "required": [
                "results",
                "total"
              ],
              "properties": {
                "_links": {
                  "$ref": "#/definitions/Links"
                },
                "results": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/GetRealmResponse"
                  }
                },
                "total": {
                  "description": "Total number of entries",
                  "type": "integer"
                }
              }
            },
            "x-go-name": "FoundRealms"
          },
          "400": {
            "$ref": "#/responses/BadRequest"
          },
          "401": {
            "$ref": "#/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/responses/Forbidden"
          },
          "409": {
            "$ref": "#/responses/Conflict"
          },
          "429": {
            "$ref": "#/responses/TooManyRequests"
          },
          "default": {
            "$ref": "#/responses/Unexpected"
          }
        }
      },
      "post": {
        "tags": [
          "realms"
        ],
        "summary": "Create new realm",
        "operationId": "create-realm",
        "parameters": [
          {
            "name": "realm",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CreateRealmRequest"
            }
          }
        ],
        "responses": {
          "201": {
            "$ref": "#/responses/Created"
          },
          "400": {
            "$ref": "#/responses/BadRequest"
          },
          "401": {
            "$ref": "#/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/responses/Forbidden"
          },
          "409": {
            "$ref": "#/responses/Conflict"
          },
          "429": {
            "$ref": "#/responses/TooManyRequests"
          },
          "default": {
            "$ref": "#/responses/Unexpected"
          }
        }
      }
    },
    "/realms/{realm_id}": {
      "get": {
        "tags": [
          "realms"
        ],
        "summary": "Get realm",
        "operationId": "get-realm",
        "parameters": [
          {
            "$ref": "#/parameters/realm_id"
          }
        ],
        "responses": {
          "200": {
            "description": "found",
            "schema": {
              "$ref": "#/definitions/GetRealmResponse"
            },
            "x-go-name": "FoundRealm"
          },
          "400": {
            "$ref": "#/responses/BadRequest"
          },
          "401": {
            "$ref": "#/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/responses/Forbidden"
          },
          "404": {
            "$ref": "#/responses/NotFound"
          },
          "429": {
            "$ref": "#/responses/TooManyRequests"
          },
          "default": {
            "$ref": "#/responses/Unexpected"
          }
        }
      },
      "put": {
        "tags": [
          "realms"
        ],
        "summary": "Update realm",
        "operationId": "update-realm",
        "parameters": [
          {
            "$ref": "#/parameters/realm_id"
          },
          {
            "name": "realm",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UpdateRealmRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "$ref": "#/responses/OK"
          },
          "400": {
            "$ref": "#/responses/BadRequest"
          },
          "401": {
            "$ref": "#/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/responses/Forbidden"
          },
          "404": {
            "$ref": "#/responses/NotFound"
          },
          "429": {
            "$ref": "#/responses/TooManyRequests"
          },
          "default": {
            "$ref": "#/responses/Unexpected"
          }
        }
      },
      "delete": {
        "tags": [
          "realms"
        ],
        "summary": "Delete realm",
        "operationId": "delete-realm",
        "parameters": [
          {
            "$ref": "#/parameters/realm_id"
          }
        ],
        "responses": {
          "200": {
            "$ref": "#/responses/OK"
          },
          "400": {
            "$ref": "#/responses/BadRequest"
          },
          "401": {
            "$ref": "#/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/responses/Forbidden"
          },
          "404": {
            "$ref": "#/responses/NotFound"
          },
          "429": {
            "$ref": "#/responses/TooManyRequests"
          },
          "default": {
            "$ref": "#/responses/Unexpected"
          }
        }
      }
    },
    "/realms/{realm_id}/users": {
      "get": {
        "tags": [
          "users"
        ],
        "summary": "List users",
        "operationId": "list-users",
        "parameters": [
          {
            "$ref": "#/parameters/realm_id"
          },
          {
            "$ref": "#/parameters/offset"
          },
          {
            "$ref": "#/parameters/limit"
          }
        ],
        "responses": {
          "200": {
            "description": "found",
            "schema": {
              "type": "object",
              "required": [
                "results",
                "total"
              ],
              "properties": {
                "_links": {
                  "$ref": "#/definitions/Links"
                },
                "results": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/GetUserResponse"
                  }
                },
                "total": {
                  "description": "Total number of entries",
                  "type": "integer"
                }
              }
            },
            "x-go-name": "FoundUsers"
          },
          "400": {
            "$ref": "#/responses/BadRequest"
          },
          "401": {
            "$ref": "#/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/responses/Forbidden"
          },
          "409": {
            "$ref": "#/responses/Conflict"
          },
          "429": {
            "$ref": "#/responses/TooManyRequests"
          },
          "default": {
            "$ref": "#/responses/Unexpected"
          }
        }
      },
      "post": {
        "tags": [
          "users"
        ],
        "summary": "Create new user",
        "operationId": "create-user",
        "parameters": [
          {
            "$ref": "#/parameters/realm_id"
          },
          {
            "name": "user",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CreateUserRequest"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "success",
            "schema": {
              "$ref": "#/definitions/CreateUserResponse"
            },
            "x-go-name": "CreatedUser"
          },
          "400": {
            "$ref": "#/responses/BadRequest"
          },
          "401": {
            "$ref": "#/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/responses/Forbidden"
          },
          "409": {
            "$ref": "#/responses/Conflict"
          },
          "429": {
            "$ref": "#/responses/TooManyRequests"
          },
          "default": {
            "$ref": "#/responses/Unexpected"
          }
        }
      }
    },
    "/realms/{realm_id}/users/{username}": {
      "get": {
        "tags": [
          "users"
        ],
        "summary": "Get user",
        "operationId": "get-user",
        "parameters": [
          {
            "$ref": "#/parameters/realm_id"
          },
          {
            "$ref": "#/parameters/username"
          }
        ],
        "responses": {
          "200": {
            "description": "found",
            "schema": {
              "$ref": "#/definitions/GetUserResponse"
            },
            "x-go-name": "FoundUser"
          },
          "400": {
            "$ref": "#/responses/BadRequest"
          },
          "401": {
            "$ref": "#/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/responses/Forbidden"
          },
          "404": {
            "$ref": "#/responses/NotFound"
          },
          "429": {
            "$ref": "#/responses/TooManyRequests"
          },
          "default": {
            "$ref": "#/responses/Unexpected"
          }
        }
      },
      "put": {
        "tags": [
          "users"
        ],
        "summary": "Update user",
        "operationId": "update-user",
        "parameters": [
          {
            "$ref": "#/parameters/realm_id"
          },
          {
            "$ref": "#/parameters/username"
          },
          {
            "name": "user",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UpdateUserRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "$ref": "#/responses/OK"
          },
          "400": {
            "$ref": "#/responses/BadRequest"
          },
          "401": {
            "$ref": "#/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/responses/Forbidden"
          },
          "404": {
            "$ref": "#/responses/NotFound"
          },
          "429": {
            "$ref": "#/responses/TooManyRequests"
          },
          "default": {
            "$ref": "#/responses/Unexpected"
          }
        }
      },
      "delete": {
        "tags": [
          "users"
        ],
        "summary": "Delete user",
        "operationId": "delete-user",
        "parameters": [
          {
            "$ref": "#/parameters/realm_id"
          },
          {
            "$ref": "#/parameters/username"
          }
        ],
        "responses": {
          "200": {
            "$ref": "#/responses/OK"
          },
          "400": {
            "$ref": "#/responses/BadRequest"
          },
          "401": {
            "$ref": "#/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/responses/Forbidden"
          },
          "404": {
            "$ref": "#/responses/NotFound"
          },
          "429": {
            "$ref": "#/responses/TooManyRequests"
          },
          "default": {
            "$ref": "#/responses/Unexpected"
          }
        }
      }
    }
  },
  "definitions": {
    "CreateRealmRequest": {
      "type": "object",
      "required": [
        "realm_id"
      ],
      "properties": {
        "description": {
          "description": "Te realm description.",
          "type": "string",
          "maxLength": 255
        },
        "realm_id": {
          "description": "The realm identifier.",
          "type": "string",
          "maxLength": 64,
          "minLength": 1,
          "pattern": "^[a-zA-Z0-9_-]*$"
        },
        "realm_metadata": {
          "description": "Additional data related to the realm",
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        }
      }
    },
    "CreateUserRequest": {
      "type": "object",
      "required": [
        "username",
        "password"
      ],
      "properties": {
        "email": {
          "description": "The user's email.",
          "type": "string",
          "format": "email"
        },
        "email_verified": {
          "description": "True if the End-User's e-mail address has been verified; otherwise false.",
          "type": "boolean"
        },
        "enabled": {
          "description": "Boolean representing if user is enabled or not.",
          "type": "boolean"
        },
        "password": {
          "description": "Initial password for this user.",
          "type": "string",
          "format": "password"
        },
        "user_metadata": {
          "description": "Additional data related to the user",
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        },
        "username": {
          "description": "User name that is unique in the realm",
          "type": "string",
          "maxLength": 320,
          "minLength": 1,
          "pattern": "^[a-zA-Z0-9!$%\u0026()*+,.\\/:;\u003c=\u003e?@\\[\\]^_{|}~-]*$"
        }
      }
    },
    "CreateUserResponse": {
      "type": "object",
      "required": [
        "user_id",
        "realm_id",
        "username"
      ],
      "properties": {
        "realm_id": {
          "description": "The realm identifier.",
          "type": "string"
        },
        "user_id": {
          "description": "Global user identifiert.",
          "type": "string"
        },
        "username": {
          "description": "User name that is unique in the realm",
          "type": "string"
        }
      }
    },
    "GetRealmResponse": {
      "type": "object",
      "required": [
        "realm_id"
      ],
      "properties": {
        "created_at": {
          "type": "string",
          "format": "date-time"
        },
        "description": {
          "description": "Te realm description.",
          "type": "string"
        },
        "realm_id": {
          "description": "The realm identifier.",
          "type": "string"
        }
      }
    },
    "GetUserResponse": {
      "type": "object",
      "required": [
        "user_id",
        "realm_id",
        "username"
      ],
      "properties": {
        "created_at": {
          "type": "string",
          "format": "date-time"
        },
        "email": {
          "description": "The user's email.",
          "type": "string",
          "format": "email"
        },
        "email_verified": {
          "description": "True if the End-User's e-mail address has been verified; otherwise false.",
          "type": "boolean"
        },
        "enabled": {
          "description": "Boolean representing if user is enabled or not.",
          "type": "boolean"
        },
        "realm_id": {
          "description": "The realm identifier.",
          "type": "string"
        },
        "user_id": {
          "description": "Global user identifiert.",
          "type": "string"
        },
        "username": {
          "description": "User name that is unique in the realm",
          "type": "string"
        }
      }
    },
    "Links": {
      "type": "object",
      "properties": {
        "next": {
          "description": "The link for the next page of results.",
          "type": "string"
        },
        "prev": {
          "description": "The link for the previous page of results.",
          "type": "string"
        }
      }
    },
    "Problem": {
      "type": "object",
      "properties": {
        "code": {
          "description": "The HTTP status code generated by the origin server for this occurrence of the problem.\n",
          "type": "integer",
          "format": "int32",
          "maximum": 600,
          "exclusiveMaximum": true,
          "minimum": 100,
          "example": 503
        },
        "detail": {
          "description": "A human readable explanation specific to this occurrence of the problem that is helpful to locate the problem and give advice on how to proceed.\n",
          "type": "string",
          "example": "Connection to database timed out"
        },
        "instance": {
          "description": "A URI reference that identifies the specific occurrence of the problem, e.g. by adding a fragment identifier or sub-path to the problem type. May be used to locate the root of this problem in the source code.\n",
          "type": "string",
          "format": "uri-reference",
          "example": "/problem/connection-error#token-info-read-timed-out"
        },
        "message": {
          "description": "A short summary of the problem type.\n",
          "type": "string",
          "example": "Service Unavailable"
        },
        "type": {
          "description": "A URI reference that uniquely identifies the problem type only in the context of the provided API. Opposed to the specification in RFC-7807, it is neither recommended to be dereferencable and point to a human-readable documentation nor globally unique for the problem type.\n",
          "type": "string",
          "format": "uri-reference",
          "default": "about:blank",
          "example": "/problem/connection-error"
        }
      }
    },
    "UpdateRealmRequest": {
      "type": "object",
      "properties": {
        "description": {
          "description": "Te realm description.",
          "type": "string",
          "maxLength": 255
        },
        "realm_metadata": {
          "description": "Additional data related to the realm",
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        }
      }
    },
    "UpdateUserRequest": {
      "type": "object",
      "properties": {
        "email": {
          "description": "The user's email.",
          "type": "string",
          "format": "email"
        },
        "email_verified": {
          "description": "True if the End-User's e-mail address has been verified; otherwise false.",
          "type": "boolean"
        },
        "enabled": {
          "description": "Boolean representing if user is enabled or not.",
          "type": "boolean"
        },
        "password": {
          "description": "Initial password for this user.",
          "type": "string",
          "format": "password"
        },
        "user_metadata": {
          "description": "Additional data related to the user",
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        }
      }
    }
  },
  "parameters": {
    "limit": {
      "type": "integer",
      "description": "The numbers of entries to return.",
      "name": "limit",
      "in": "query"
    },
    "offset": {
      "type": "integer",
      "description": "The number of items to skip before starting to collect the result set.",
      "name": "offset",
      "in": "query"
    },
    "realm_id": {
      "type": "string",
      "description": "Realm id.",
      "name": "realm_id",
      "in": "path",
      "required": true
    },
    "username": {
      "type": "string",
      "description": "Username.",
      "name": "username",
      "in": "path",
      "required": true
    }
  },
  "responses": {
    "BadRequest": {
      "description": "Invalid request body.",
      "schema": {
        "$ref": "#/definitions/Problem"
      },
      "x-go-name": "BadRequest"
    },
    "Conflict": {
      "description": "Already exists.",
      "schema": {
        "$ref": "#/definitions/Problem"
      },
      "x-go-name": "Conflict"
    },
    "Created": {
      "description": "Successfully created.",
      "x-go-name": "Created"
    },
    "Forbidden": {
      "description": "Insufficient scope.",
      "schema": {
        "$ref": "#/definitions/Problem"
      },
      "x-go-name": "Forbidden"
    },
    "InternalServerError": {
      "description": "Internal Server Error",
      "schema": {
        "$ref": "#/definitions/Problem"
      },
      "x-go-name": "Internal Server Error"
    },
    "NotFound": {
      "description": "Not found.",
      "schema": {
        "$ref": "#/definitions/Problem"
      },
      "x-go-name": "NotFound"
    },
    "OK": {
      "description": "Successfully created.",
      "x-go-name": "OK"
    },
    "TooManyRequests": {
      "description": "Rate limiting",
      "schema": {
        "$ref": "#/definitions/Problem"
      },
      "x-go-name": "Too Many Requests"
    },
    "Unauthorized": {
      "description": "Invalid token.",
      "schema": {
        "$ref": "#/definitions/Problem"
      },
      "x-go-name": "Unauthorized"
    },
    "Unexpected": {
      "description": "Unexpected error",
      "schema": {
        "$ref": "#/definitions/Problem"
      },
      "x-go-name": "Unexpected"
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "swagger": "2.0",
  "info": {
    "description": "This is a REST API reference for the Tribe Admin",
    "title": "Tribe",
    "version": "v1alpha"
  },
  "basePath": "/v1",
  "paths": {
    "/-/healthy": {
      "get": {
        "description": "An endpoint which responds health checks\n",
        "tags": [
          "healthz"
        ],
        "summary": "Health check",
        "responses": {
          "200": {
            "description": "Success"
          },
          "503": {
            "description": "Service Unavailable",
            "schema": {
              "$ref": "#/definitions/Problem"
            }
          }
        }
      }
    },
    "/-/ready": {
      "get": {
        "description": "An endpoint which responds readiness checks. This probe is\ncalled to check whether the service is ready to receive traffic.\n",
        "tags": [
          "healthz"
        ],
        "summary": "Readiness check",
        "responses": {
          "200": {
            "description": "Success"
          },
          "503": {
            "description": "Service Unavailable",
            "schema": {
              "$ref": "#/definitions/Problem"
            }
          }
        }
      }
    },
    "/realms": {
      "get": {
        "tags": [
          "realms"
        ],
        "summary": "List realms",
        "operationId": "list-realms",
        "parameters": [
          {
            "type": "integer",
            "description": "The number of items to skip before starting to collect the result set.",
            "name": "offset",
            "in": "query"
          },
          {
            "minimum": 0,
            "type": "integer",
            "description": "The numbers of entries to return.",
            "name": "limit",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "found",
            "schema": {
              "type": "object",
              "required": [
                "results",
                "total"
              ],
              "properties": {
                "_links": {
                  "$ref": "#/definitions/Links"
                },
                "results": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/GetRealmResponse"
                  }
                },
                "total": {
                  "description": "Total number of entries",
                  "type": "integer"
                }
              }
            },
            "x-go-name": "FoundRealms"
          },
          "400": {
            "description": "Invalid request body.",
            "schema": {
              "$ref": "#/definitions/Problem"
            },
            "x-go-name": "BadRequest"
          },
          "401": {
            "description": "Invalid token.",
            "schema": {
              "$ref": "#/definitions/Problem"
            },
            "x-go-name": "Unauthorized"
          },
          "403": {
            "description": "Insufficient scope.",
            "schema": {
              "$ref": "#/definitions/Problem"
            },
            "x-go-name": "Forbidden"
          },
          "409": {
            "description": "Already exists.",
            "schema": {
              "$ref": "#/definitions/Problem"
            },
            "x-go-name": "Conflict"
          },
          "429": {
            "description": "Rate limiting",
            "schema": {
              "$ref": "#/definitions/Problem"
            },
            "x-go-name": "Too Many Requests"
          },
          "default": {
            "description": "Unexpected error",
            "schema": {
              "$ref": "#/definitions/Problem"
            },
            "x-go-name": "Unexpected"
          }
        }
      },
      "post": {
        "tags": [
          "realms"
        ],
        "summary": "Create new realm",
        "operationId": "create-realm",
        "parameters": [
          {
            "name": "realm",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CreateRealmRequest"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Successfully created.",
            "x-go-name": "Created"
          },
          "400": {
            "description": "Invalid request body.",
            "schema": {
              "$ref": "#/definitions/Problem"
            },
            "x-go-name": "BadRequest"
          },
          "401": {
            "description": "Invalid token.",
            "schema": {
              "$ref": "#/definitions/Problem"
            },
            "x-go-name": "Unauthorized"
          },
          "403": {
            "description": "Insufficient scope.",
            "schema": {
              "$ref": "#/definitions/Problem"
            },
            "x-go-name": "Forbidden"
          },
          "409": {
            "description": "Already exists.",
            "schema": {
              "$ref": "#/definitions/Problem"
            },
            "x-go-name": "Conflict"
          },
          "429": {
            "description": "Rate limiting",
            "schema": {
              "$ref": "#/definitions/Problem"
            },
            "x-go-name": "Too Many Requests"
          },
          "default": {
            "description": "Unexpected error",
            "schema": {
              "$ref": "#/definitions/Problem"
            },
            "x-go-name": "Unexpected"
          }
        }
      }
    },
    "/realms/{realm_id}": {
      "get": {
        "tags": [
          "realms"
        ],
        "summary": "Get realm",
        "operationId": "get-realm",
        "parameters": [
          {
            "type": "string",
            "description": "Realm id.",
            "name": "realm_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "found",
            "schema": {
              "$ref": "#/definitions/GetRealmResponse"
            },
            "x-go-name": "FoundRealm"
          },
          "400": {
            "description": "Invalid request body.",
            "schema": {
              "$ref": "#/definitions/Problem"
            },
            "x-go-name": "BadRequest"
          },
          "401": {
            "description": "Invalid token.",
            "schema": {
              "$ref": "#/definitions/Problem"
            },
            "x-go-name": "Unauthorized"
          },
          "403": {
            "description": "Insufficient scope.",
            "schema": {
              "$ref": "#/definitions/Problem"
            },
            "x-go-name": "Forbidden"
          },
          "404": {
            "description": "Not found.",
            "schema": {
              "$ref": "#/definitions/Problem"
            },
            "x-go-name": "NotFound"
          },
          "429": {
            "description": "Rate limiting",
            "schema": {
              "$ref": "#/definitions/Problem"
            },
            "x-go-name": "Too Many Requests"
          },
          "default": {
            "description": "Unexpected error",
            "schema": {
              "$ref": "#/definitions/Problem"
            },
            "x-go-name": "Unexpected"
          }
        }
      },
      "put": {
        "tags": [
          "realms"
        ],
        "summary": "Update realm",
        "operationId": "update-realm",
        "parameters": [
          {
            "type": "string",
            "description": "Realm id.",
            "name": "realm_id",
            "in": "path",
            "required": true
          },
          {
            "name": "realm",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UpdateRealmRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully created.",
            "x-go-name": "OK"
          },
          "400": {
            "description": "Invalid request body.",
            "schema": {
              "$ref": "#/definitions/Problem"
            },
            "x-go-name": "BadRequest"
          },
          "401": {
            "description": "Invalid token.",
            "schema": {
              "$ref": "#/definitions/Problem"
            },
            "x-go-name": "Unauthorized"
          },
          "403": {
            "description": "Insufficient scope.",
            "schema": {
              "$ref": "#/definitions/Problem"
            },
            "x-go-name": "Forbidden"
          },
          "404": {
            "description": "Not found.",
            "schema": {
              "$ref": "#/definitions/Problem"
            },
            "x-go-name": "NotFound"
          },
          "429": {
            "description": "Rate limiting",
            "schema": {
              "$ref": "#/definitions/Problem"
            },
            "x-go-name": "Too Many Requests"
          },
          "default": {
            "description": "Unexpected error",
            "schema": {
              "$ref": "#/definitions/Problem"
            },
            "x-go-name": "Unexpected"
          }
        }
      },
      "delete": {
        "tags": [
          "realms"
        ],
        "summary": "Delete realm",
        "operationId": "delete-realm",
        "parameters": [
          {
            "type": "string",
            "description": "Realm id.",
            "name": "realm_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully created.",
            "x-go-name": "OK"
          },
          "400": {
            "description": "Invalid request body.",
            "schema": {
              "$ref": "#/definitions/Problem"
            },
            "x-go-name": "BadRequest"
          },
          "401": {
            "description": "Invalid token.",
            "schema": {
              "$ref": "#/definitions/Problem"
            },
            "x-go-name": "Unauthorized"
          },
          "403": {
            "description": "Insufficient scope.",
            "schema": {
              "$ref": "#/definitions/Problem"
            },
            "x-go-name": "Forbidden"
          },
          "404": {
            "description": "Not found.",
            "schema": {
              "$ref": "#/definitions/Problem"
            },
            "x-go-name": "NotFound"
          },
          "429": {
            "description": "Rate limiting",
            "schema": {
              "$ref": "#/definitions/Problem"
            },
            "x-go-name": "Too Many Requests"
          },
          "default": {
            "description": "Unexpected error",
            "schema": {
              "$ref": "#/definitions/Problem"
            },
            "x-go-name": "Unexpected"
          }
        }
      }
    },
    "/realms/{realm_id}/users": {
      "get": {
        "tags": [
          "users"
        ],
        "summary": "List users",
        "operationId": "list-users",
        "parameters": [
          {
            "type": "string",
            "description": "Realm id.",
            "name": "realm_id",
            "in": "path",
            "required": true
          },
          {
            "type": "integer",
            "description": "The number of items to skip before starting to collect the result set.",
            "name": "offset",
            "in": "query"
          },
          {
            "minimum": 0,
            "type": "integer",
            "description": "The numbers of entries to return.",
            "name": "limit",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "found",
            "schema": {
              "type": "object",
              "required": [
                "results",
                "total"
              ],
              "properties": {
                "_links": {
                  "$ref": "#/definitions/Links"
                },
                "results": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/GetUserResponse"
                  }
                },
                "total": {
                  "description": "Total number of entries",
                  "type": "integer"
                }
              }
            },
            "x-go-name": "FoundUsers"
          },
          "400": {
            "description": "Invalid request body.",
            "schema": {
              "$ref": "#/definitions/Problem"
            },
            "x-go-name": "BadRequest"
          },
          "401": {
            "description": "Invalid token.",
            "schema": {
              "$ref": "#/definitions/Problem"
            },
            "x-go-name": "Unauthorized"
          },
          "403": {
            "description": "Insufficient scope.",
            "schema": {
              "$ref": "#/definitions/Problem"
            },
            "x-go-name": "Forbidden"
          },
          "409": {
            "description": "Already exists.",
            "schema": {
              "$ref": "#/definitions/Problem"
            },
            "x-go-name": "Conflict"
          },
          "429": {
            "description": "Rate limiting",
            "schema": {
              "$ref": "#/definitions/Problem"
            },
            "x-go-name": "Too Many Requests"
          },
          "default": {
            "description": "Unexpected error",
            "schema": {
              "$ref": "#/definitions/Problem"
            },
            "x-go-name": "Unexpected"
          }
        }
      },
      "post": {
        "tags": [
          "users"
        ],
        "summary": "Create new user",
        "operationId": "create-user",
        "parameters": [
          {
            "type": "string",
            "description": "Realm id.",
            "name": "realm_id",
            "in": "path",
            "required": true
          },
          {
            "name": "user",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CreateUserRequest"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "success",
            "schema": {
              "$ref": "#/definitions/CreateUserResponse"
            },
            "x-go-name": "CreatedUser"
          },
          "400": {
            "description": "Invalid request body.",
            "schema": {
              "$ref": "#/definitions/Problem"
            },
            "x-go-name": "BadRequest"
          },
          "401": {
            "description": "Invalid token.",
            "schema": {
              "$ref": "#/definitions/Problem"
            },
            "x-go-name": "Unauthorized"
          },
          "403": {
            "description": "Insufficient scope.",
            "schema": {
              "$ref": "#/definitions/Problem"
            },
            "x-go-name": "Forbidden"
          },
          "409": {
            "description": "Already exists.",
            "schema": {
              "$ref": "#/definitions/Problem"
            },
            "x-go-name": "Conflict"
          },
          "429": {
            "description": "Rate limiting",
            "schema": {
              "$ref": "#/definitions/Problem"
            },
            "x-go-name": "Too Many Requests"
          },
          "default": {
            "description": "Unexpected error",
            "schema": {
              "$ref": "#/definitions/Problem"
            },
            "x-go-name": "Unexpected"
          }
        }
      }
    },
    "/realms/{realm_id}/users/{username}": {
      "get": {
        "tags": [
          "users"
        ],
        "summary": "Get user",
        "operationId": "get-user",
        "parameters": [
          {
            "type": "string",
            "description": "Realm id.",
            "name": "realm_id",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "Username.",
            "name": "username",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "found",
            "schema": {
              "$ref": "#/definitions/GetUserResponse"
            },
            "x-go-name": "FoundUser"
          },
          "400": {
            "description": "Invalid request body.",
            "schema": {
              "$ref": "#/definitions/Problem"
            },
            "x-go-name": "BadRequest"
          },
          "401": {
            "description": "Invalid token.",
            "schema": {
              "$ref": "#/definitions/Problem"
            },
            "x-go-name": "Unauthorized"
          },
          "403": {
            "description": "Insufficient scope.",
            "schema": {
              "$ref": "#/definitions/Problem"
            },
            "x-go-name": "Forbidden"
          },
          "404": {
            "description": "Not found.",
            "schema": {
              "$ref": "#/definitions/Problem"
            },
            "x-go-name": "NotFound"
          },
          "429": {
            "description": "Rate limiting",
            "schema": {
              "$ref": "#/definitions/Problem"
            },
            "x-go-name": "Too Many Requests"
          },
          "default": {
            "description": "Unexpected error",
            "schema": {
              "$ref": "#/definitions/Problem"
            },
            "x-go-name": "Unexpected"
          }
        }
      },
      "put": {
        "tags": [
          "users"
        ],
        "summary": "Update user",
        "operationId": "update-user",
        "parameters": [
          {
            "type": "string",
            "description": "Realm id.",
            "name": "realm_id",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "Username.",
            "name": "username",
            "in": "path",
            "required": true
          },
          {
            "name": "user",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UpdateUserRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully created.",
            "x-go-name": "OK"
          },
          "400": {
            "description": "Invalid request body.",
            "schema": {
              "$ref": "#/definitions/Problem"
            },
            "x-go-name": "BadRequest"
          },
          "401": {
            "description": "Invalid token.",
            "schema": {
              "$ref": "#/definitions/Problem"
            },
            "x-go-name": "Unauthorized"
          },
          "403": {
            "description": "Insufficient scope.",
            "schema": {
              "$ref": "#/definitions/Problem"
            },
            "x-go-name": "Forbidden"
          },
          "404": {
            "description": "Not found.",
            "schema": {
              "$ref": "#/definitions/Problem"
            },
            "x-go-name": "NotFound"
          },
          "429": {
            "description": "Rate limiting",
            "schema": {
              "$ref": "#/definitions/Problem"
            },
            "x-go-name": "Too Many Requests"
          },
          "default": {
            "description": "Unexpected error",
            "schema": {
              "$ref": "#/definitions/Problem"
            },
            "x-go-name": "Unexpected"
          }
        }
      },
      "delete": {
        "tags": [
          "users"
        ],
        "summary": "Delete user",
        "operationId": "delete-user",
        "parameters": [
          {
            "type": "string",
            "description": "Realm id.",
            "name": "realm_id",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "Username.",
            "name": "username",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully created.",
            "x-go-name": "OK"
          },
          "400": {
            "description": "Invalid request body.",
            "schema": {
              "$ref": "#/definitions/Problem"
            },
            "x-go-name": "BadRequest"
          },
          "401": {
            "description": "Invalid token.",
            "schema": {
              "$ref": "#/definitions/Problem"
            },
            "x-go-name": "Unauthorized"
          },
          "403": {
            "description": "Insufficient scope.",
            "schema": {
              "$ref": "#/definitions/Problem"
            },
            "x-go-name": "Forbidden"
          },
          "404": {
            "description": "Not found.",
            "schema": {
              "$ref": "#/definitions/Problem"
            },
            "x-go-name": "NotFound"
          },
          "429": {
            "description": "Rate limiting",
            "schema": {
              "$ref": "#/definitions/Problem"
            },
            "x-go-name": "Too Many Requests"
          },
          "default": {
            "description": "Unexpected error",
            "schema": {
              "$ref": "#/definitions/Problem"
            },
            "x-go-name": "Unexpected"
          }
        }
      }
    }
  },
  "definitions": {
    "CreateRealmRequest": {
      "type": "object",
      "required": [
        "realm_id"
      ],
      "properties": {
        "description": {
          "description": "Te realm description.",
          "type": "string",
          "maxLength": 255
        },
        "realm_id": {
          "description": "The realm identifier.",
          "type": "string",
          "maxLength": 64,
          "minLength": 1,
          "pattern": "^[a-zA-Z0-9_-]*$"
        },
        "realm_metadata": {
          "description": "Additional data related to the realm",
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        }
      }
    },
    "CreateUserRequest": {
      "type": "object",
      "required": [
        "username",
        "password"
      ],
      "properties": {
        "email": {
          "description": "The user's email.",
          "type": "string",
          "format": "email"
        },
        "email_verified": {
          "description": "True if the End-User's e-mail address has been verified; otherwise false.",
          "type": "boolean"
        },
        "enabled": {
          "description": "Boolean representing if user is enabled or not.",
          "type": "boolean"
        },
        "password": {
          "description": "Initial password for this user.",
          "type": "string",
          "format": "password"
        },
        "user_metadata": {
          "description": "Additional data related to the user",
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        },
        "username": {
          "description": "User name that is unique in the realm",
          "type": "string",
          "maxLength": 320,
          "minLength": 1,
          "pattern": "^[a-zA-Z0-9!$%\u0026()*+,.\\/:;\u003c=\u003e?@\\[\\]^_{|}~-]*$"
        }
      }
    },
    "CreateUserResponse": {
      "type": "object",
      "required": [
        "user_id",
        "realm_id",
        "username"
      ],
      "properties": {
        "realm_id": {
          "description": "The realm identifier.",
          "type": "string"
        },
        "user_id": {
          "description": "Global user identifiert.",
          "type": "string"
        },
        "username": {
          "description": "User name that is unique in the realm",
          "type": "string"
        }
      }
    },
    "GetRealmResponse": {
      "type": "object",
      "required": [
        "realm_id"
      ],
      "properties": {
        "created_at": {
          "type": "string",
          "format": "date-time"
        },
        "description": {
          "description": "Te realm description.",
          "type": "string"
        },
        "realm_id": {
          "description": "The realm identifier.",
          "type": "string"
        }
      }
    },
    "GetUserResponse": {
      "type": "object",
      "required": [
        "user_id",
        "realm_id",
        "username"
      ],
      "properties": {
        "created_at": {
          "type": "string",
          "format": "date-time"
        },
        "email": {
          "description": "The user's email.",
          "type": "string",
          "format": "email"
        },
        "email_verified": {
          "description": "True if the End-User's e-mail address has been verified; otherwise false.",
          "type": "boolean"
        },
        "enabled": {
          "description": "Boolean representing if user is enabled or not.",
          "type": "boolean"
        },
        "realm_id": {
          "description": "The realm identifier.",
          "type": "string"
        },
        "user_id": {
          "description": "Global user identifiert.",
          "type": "string"
        },
        "username": {
          "description": "User name that is unique in the realm",
          "type": "string"
        }
      }
    },
    "Links": {
      "type": "object",
      "properties": {
        "next": {
          "description": "The link for the next page of results.",
          "type": "string"
        },
        "prev": {
          "description": "The link for the previous page of results.",
          "type": "string"
        }
      }
    },
    "Problem": {
      "type": "object",
      "properties": {
        "code": {
          "description": "The HTTP status code generated by the origin server for this occurrence of the problem.\n",
          "type": "integer",
          "format": "int32",
          "maximum": 600,
          "exclusiveMaximum": true,
          "minimum": 100,
          "example": 503
        },
        "detail": {
          "description": "A human readable explanation specific to this occurrence of the problem that is helpful to locate the problem and give advice on how to proceed.\n",
          "type": "string",
          "example": "Connection to database timed out"
        },
        "instance": {
          "description": "A URI reference that identifies the specific occurrence of the problem, e.g. by adding a fragment identifier or sub-path to the problem type. May be used to locate the root of this problem in the source code.\n",
          "type": "string",
          "format": "uri-reference",
          "example": "/problem/connection-error#token-info-read-timed-out"
        },
        "message": {
          "description": "A short summary of the problem type.\n",
          "type": "string",
          "example": "Service Unavailable"
        },
        "type": {
          "description": "A URI reference that uniquely identifies the problem type only in the context of the provided API. Opposed to the specification in RFC-7807, it is neither recommended to be dereferencable and point to a human-readable documentation nor globally unique for the problem type.\n",
          "type": "string",
          "format": "uri-reference",
          "default": "about:blank",
          "example": "/problem/connection-error"
        }
      }
    },
    "UpdateRealmRequest": {
      "type": "object",
      "properties": {
        "description": {
          "description": "Te realm description.",
          "type": "string",
          "maxLength": 255
        },
        "realm_metadata": {
          "description": "Additional data related to the realm",
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        }
      }
    },
    "UpdateUserRequest": {
      "type": "object",
      "properties": {
        "email": {
          "description": "The user's email.",
          "type": "string",
          "format": "email"
        },
        "email_verified": {
          "description": "True if the End-User's e-mail address has been verified; otherwise false.",
          "type": "boolean"
        },
        "enabled": {
          "description": "Boolean representing if user is enabled or not.",
          "type": "boolean"
        },
        "password": {
          "description": "Initial password for this user.",
          "type": "string",
          "format": "password"
        },
        "user_metadata": {
          "description": "Additional data related to the user",
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        }
      }
    }
  },
  "parameters": {
    "limit": {
      "minimum": 0,
      "type": "integer",
      "description": "The numbers of entries to return.",
      "name": "limit",
      "in": "query"
    },
    "offset": {
      "type": "integer",
      "description": "The number of items to skip before starting to collect the result set.",
      "name": "offset",
      "in": "query"
    },
    "realm_id": {
      "type": "string",
      "description": "Realm id.",
      "name": "realm_id",
      "in": "path",
      "required": true
    },
    "username": {
      "type": "string",
      "description": "Username.",
      "name": "username",
      "in": "path",
      "required": true
    }
  },
  "responses": {
    "BadRequest": {
      "description": "Invalid request body.",
      "schema": {
        "$ref": "#/definitions/Problem"
      },
      "x-go-name": "BadRequest"
    },
    "Conflict": {
      "description": "Already exists.",
      "schema": {
        "$ref": "#/definitions/Problem"
      },
      "x-go-name": "Conflict"
    },
    "Created": {
      "description": "Successfully created.",
      "x-go-name": "Created"
    },
    "Forbidden": {
      "description": "Insufficient scope.",
      "schema": {
        "$ref": "#/definitions/Problem"
      },
      "x-go-name": "Forbidden"
    },
    "InternalServerError": {
      "description": "Internal Server Error",
      "schema": {
        "$ref": "#/definitions/Problem"
      },
      "x-go-name": "Internal Server Error"
    },
    "NotFound": {
      "description": "Not found.",
      "schema": {
        "$ref": "#/definitions/Problem"
      },
      "x-go-name": "NotFound"
    },
    "OK": {
      "description": "Successfully created.",
      "x-go-name": "OK"
    },
    "TooManyRequests": {
      "description": "Rate limiting",
      "schema": {
        "$ref": "#/definitions/Problem"
      },
      "x-go-name": "Too Many Requests"
    },
    "Unauthorized": {
      "description": "Invalid token.",
      "schema": {
        "$ref": "#/definitions/Problem"
      },
      "x-go-name": "Unauthorized"
    },
    "Unexpected": {
      "description": "Unexpected error",
      "schema": {
        "$ref": "#/definitions/Problem"
      },
      "x-go-name": "Unexpected"
    }
  }
}`))
}
