// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/grepplabs/tribe/api/v1/models"
)

// ListUsersBadRequestCode is the HTTP code returned for type ListUsersBadRequest
const ListUsersBadRequestCode int = 400

/*ListUsersBadRequest Invalid request body.

swagger:response listUsersBadRequest
*/
type ListUsersBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Problem `json:"body,omitempty"`
}

// NewListUsersBadRequest creates ListUsersBadRequest with default headers values
func NewListUsersBadRequest() *ListUsersBadRequest {

	return &ListUsersBadRequest{}
}

// WithPayload adds the payload to the list users bad request response
func (o *ListUsersBadRequest) WithPayload(payload *models.Problem) *ListUsersBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list users bad request response
func (o *ListUsersBadRequest) SetPayload(payload *models.Problem) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListUsersBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListUsersUnauthorizedCode is the HTTP code returned for type ListUsersUnauthorized
const ListUsersUnauthorizedCode int = 401

/*ListUsersUnauthorized Invalid token.

swagger:response listUsersUnauthorized
*/
type ListUsersUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Problem `json:"body,omitempty"`
}

// NewListUsersUnauthorized creates ListUsersUnauthorized with default headers values
func NewListUsersUnauthorized() *ListUsersUnauthorized {

	return &ListUsersUnauthorized{}
}

// WithPayload adds the payload to the list users unauthorized response
func (o *ListUsersUnauthorized) WithPayload(payload *models.Problem) *ListUsersUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list users unauthorized response
func (o *ListUsersUnauthorized) SetPayload(payload *models.Problem) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListUsersUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListUsersForbiddenCode is the HTTP code returned for type ListUsersForbidden
const ListUsersForbiddenCode int = 403

/*ListUsersForbidden Insufficient scope.

swagger:response listUsersForbidden
*/
type ListUsersForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Problem `json:"body,omitempty"`
}

// NewListUsersForbidden creates ListUsersForbidden with default headers values
func NewListUsersForbidden() *ListUsersForbidden {

	return &ListUsersForbidden{}
}

// WithPayload adds the payload to the list users forbidden response
func (o *ListUsersForbidden) WithPayload(payload *models.Problem) *ListUsersForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list users forbidden response
func (o *ListUsersForbidden) SetPayload(payload *models.Problem) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListUsersForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListUsersConflictCode is the HTTP code returned for type ListUsersConflict
const ListUsersConflictCode int = 409

/*ListUsersConflict Already exists.

swagger:response listUsersConflict
*/
type ListUsersConflict struct {

	/*
	  In: Body
	*/
	Payload *models.Problem `json:"body,omitempty"`
}

// NewListUsersConflict creates ListUsersConflict with default headers values
func NewListUsersConflict() *ListUsersConflict {

	return &ListUsersConflict{}
}

// WithPayload adds the payload to the list users conflict response
func (o *ListUsersConflict) WithPayload(payload *models.Problem) *ListUsersConflict {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list users conflict response
func (o *ListUsersConflict) SetPayload(payload *models.Problem) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListUsersConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(409)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListUsersTooManyRequestsCode is the HTTP code returned for type ListUsersTooManyRequests
const ListUsersTooManyRequestsCode int = 429

/*ListUsersTooManyRequests Rate limiting

swagger:response listUsersTooManyRequests
*/
type ListUsersTooManyRequests struct {

	/*
	  In: Body
	*/
	Payload *models.Problem `json:"body,omitempty"`
}

// NewListUsersTooManyRequests creates ListUsersTooManyRequests with default headers values
func NewListUsersTooManyRequests() *ListUsersTooManyRequests {

	return &ListUsersTooManyRequests{}
}

// WithPayload adds the payload to the list users too many requests response
func (o *ListUsersTooManyRequests) WithPayload(payload *models.Problem) *ListUsersTooManyRequests {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list users too many requests response
func (o *ListUsersTooManyRequests) SetPayload(payload *models.Problem) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListUsersTooManyRequests) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(429)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*ListUsersDefault Unexpected error

swagger:response listUsersDefault
*/
type ListUsersDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Problem `json:"body,omitempty"`
}

// NewListUsersDefault creates ListUsersDefault with default headers values
func NewListUsersDefault(code int) *ListUsersDefault {
	if code <= 0 {
		code = 500
	}

	return &ListUsersDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the list users default response
func (o *ListUsersDefault) WithStatusCode(code int) *ListUsersDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the list users default response
func (o *ListUsersDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the list users default response
func (o *ListUsersDefault) WithPayload(payload *models.Problem) *ListUsersDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list users default response
func (o *ListUsersDefault) SetPayload(payload *models.Problem) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListUsersDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
