// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreateRealmRequest create realm request
//
// swagger:model CreateRealmRequest
type CreateRealmRequest struct {

	// Te realm description.
	// Max Length: 255
	Description string `json:"description,omitempty"`

	// The realm identifier.
	// Required: true
	// Max Length: 64
	// Min Length: 1
	// Pattern: ^[a-zA-Z0-9_-]*$
	RealmID *string `json:"realm_id"`

	// Additional data related to the realm
	RealmMetadata map[string]string `json:"realm_metadata,omitempty"`
}

// Validate validates this create realm request
func (m *CreateRealmRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDescription(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRealmID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateRealmRequest) validateDescription(formats strfmt.Registry) error {
	if swag.IsZero(m.Description) { // not required
		return nil
	}

	if err := validate.MaxLength("description", "body", m.Description, 255); err != nil {
		return err
	}

	return nil
}

func (m *CreateRealmRequest) validateRealmID(formats strfmt.Registry) error {

	if err := validate.Required("realm_id", "body", m.RealmID); err != nil {
		return err
	}

	if err := validate.MinLength("realm_id", "body", *m.RealmID, 1); err != nil {
		return err
	}

	if err := validate.MaxLength("realm_id", "body", *m.RealmID, 64); err != nil {
		return err
	}

	if err := validate.Pattern("realm_id", "body", *m.RealmID, `^[a-zA-Z0-9_-]*$`); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this create realm request based on context it is used
func (m *CreateRealmRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateRealmRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateRealmRequest) UnmarshalBinary(b []byte) error {
	var res CreateRealmRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
