// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreateUserResponse create user response
//
// swagger:model CreateUserResponse
type CreateUserResponse struct {

	// The realm identifier.
	// Required: true
	RealmID *string `json:"realm_id"`

	// Global user identifiert.
	// Required: true
	UserID *string `json:"user_id"`

	// User name that is unique in the realm
	// Required: true
	Username *string `json:"username"`
}

// Validate validates this create user response
func (m *CreateUserResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRealmID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUsername(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateUserResponse) validateRealmID(formats strfmt.Registry) error {

	if err := validate.Required("realm_id", "body", m.RealmID); err != nil {
		return err
	}

	return nil
}

func (m *CreateUserResponse) validateUserID(formats strfmt.Registry) error {

	if err := validate.Required("user_id", "body", m.UserID); err != nil {
		return err
	}

	return nil
}

func (m *CreateUserResponse) validateUsername(formats strfmt.Registry) error {

	if err := validate.Required("username", "body", m.Username); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CreateUserResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateUserResponse) UnmarshalBinary(b []byte) error {
	var res CreateUserResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
