// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Problem problem
//
// swagger:model Problem
type Problem struct {

	// The HTTP status code generated by the origin server for this occurrence of the problem.
	//
	// Maximum: < 600
	// Minimum: 100
	Code int32 `json:"code,omitempty"`

	// A human readable explanation specific to this occurrence of the problem that is helpful to locate the problem and give advice on how to proceed.
	//
	Detail string `json:"detail,omitempty"`

	// A URI reference that identifies the specific occurrence of the problem, e.g. by adding a fragment identifier or sub-path to the problem type. May be used to locate the root of this problem in the source code.
	//
	Instance string `json:"instance,omitempty"`

	// A short summary of the problem type.
	//
	Message string `json:"message,omitempty"`

	// A URI reference that uniquely identifies the problem type only in the context of the provided API. Opposed to the specification in RFC-7807, it is neither recommended to be dereferencable and point to a human-readable documentation nor globally unique for the problem type.
	//
	Type *string `json:"type,omitempty"`
}

// Validate validates this problem
func (m *Problem) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCode(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Problem) validateCode(formats strfmt.Registry) error {

	if swag.IsZero(m.Code) { // not required
		return nil
	}

	if err := validate.MinimumInt("code", "body", int64(m.Code), 100, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("code", "body", int64(m.Code), 600, true); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Problem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Problem) UnmarshalBinary(b []byte) error {
	var res Problem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
