// Code generated by go-swagger; DO NOT EDIT.

package realms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/grepplabs/tribe/api/v1/models"
)

// CreateRealmCreatedCode is the HTTP code returned for type CreateRealmCreated
const CreateRealmCreatedCode int = 201

/*CreateRealmCreated Successfully created.

swagger:response createRealmCreated
*/
type CreateRealmCreated struct {
}

// NewCreateRealmCreated creates CreateRealmCreated with default headers values
func NewCreateRealmCreated() *CreateRealmCreated {

	return &CreateRealmCreated{}
}

// WriteResponse to the client
func (o *CreateRealmCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// CreateRealmBadRequestCode is the HTTP code returned for type CreateRealmBadRequest
const CreateRealmBadRequestCode int = 400

/*CreateRealmBadRequest Invalid request body.

swagger:response createRealmBadRequest
*/
type CreateRealmBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Problem `json:"body,omitempty"`
}

// NewCreateRealmBadRequest creates CreateRealmBadRequest with default headers values
func NewCreateRealmBadRequest() *CreateRealmBadRequest {

	return &CreateRealmBadRequest{}
}

// WithPayload adds the payload to the create realm bad request response
func (o *CreateRealmBadRequest) WithPayload(payload *models.Problem) *CreateRealmBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create realm bad request response
func (o *CreateRealmBadRequest) SetPayload(payload *models.Problem) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateRealmBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateRealmUnauthorizedCode is the HTTP code returned for type CreateRealmUnauthorized
const CreateRealmUnauthorizedCode int = 401

/*CreateRealmUnauthorized Invalid token.

swagger:response createRealmUnauthorized
*/
type CreateRealmUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Problem `json:"body,omitempty"`
}

// NewCreateRealmUnauthorized creates CreateRealmUnauthorized with default headers values
func NewCreateRealmUnauthorized() *CreateRealmUnauthorized {

	return &CreateRealmUnauthorized{}
}

// WithPayload adds the payload to the create realm unauthorized response
func (o *CreateRealmUnauthorized) WithPayload(payload *models.Problem) *CreateRealmUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create realm unauthorized response
func (o *CreateRealmUnauthorized) SetPayload(payload *models.Problem) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateRealmUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateRealmForbiddenCode is the HTTP code returned for type CreateRealmForbidden
const CreateRealmForbiddenCode int = 403

/*CreateRealmForbidden Insufficient scope.

swagger:response createRealmForbidden
*/
type CreateRealmForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Problem `json:"body,omitempty"`
}

// NewCreateRealmForbidden creates CreateRealmForbidden with default headers values
func NewCreateRealmForbidden() *CreateRealmForbidden {

	return &CreateRealmForbidden{}
}

// WithPayload adds the payload to the create realm forbidden response
func (o *CreateRealmForbidden) WithPayload(payload *models.Problem) *CreateRealmForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create realm forbidden response
func (o *CreateRealmForbidden) SetPayload(payload *models.Problem) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateRealmForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateRealmConflictCode is the HTTP code returned for type CreateRealmConflict
const CreateRealmConflictCode int = 409

/*CreateRealmConflict Already exists.

swagger:response createRealmConflict
*/
type CreateRealmConflict struct {

	/*
	  In: Body
	*/
	Payload *models.Problem `json:"body,omitempty"`
}

// NewCreateRealmConflict creates CreateRealmConflict with default headers values
func NewCreateRealmConflict() *CreateRealmConflict {

	return &CreateRealmConflict{}
}

// WithPayload adds the payload to the create realm conflict response
func (o *CreateRealmConflict) WithPayload(payload *models.Problem) *CreateRealmConflict {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create realm conflict response
func (o *CreateRealmConflict) SetPayload(payload *models.Problem) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateRealmConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(409)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateRealmTooManyRequestsCode is the HTTP code returned for type CreateRealmTooManyRequests
const CreateRealmTooManyRequestsCode int = 429

/*CreateRealmTooManyRequests Rate limiting

swagger:response createRealmTooManyRequests
*/
type CreateRealmTooManyRequests struct {

	/*
	  In: Body
	*/
	Payload *models.Problem `json:"body,omitempty"`
}

// NewCreateRealmTooManyRequests creates CreateRealmTooManyRequests with default headers values
func NewCreateRealmTooManyRequests() *CreateRealmTooManyRequests {

	return &CreateRealmTooManyRequests{}
}

// WithPayload adds the payload to the create realm too many requests response
func (o *CreateRealmTooManyRequests) WithPayload(payload *models.Problem) *CreateRealmTooManyRequests {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create realm too many requests response
func (o *CreateRealmTooManyRequests) SetPayload(payload *models.Problem) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateRealmTooManyRequests) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(429)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*CreateRealmDefault Unexpected error

swagger:response createRealmDefault
*/
type CreateRealmDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Problem `json:"body,omitempty"`
}

// NewCreateRealmDefault creates CreateRealmDefault with default headers values
func NewCreateRealmDefault(code int) *CreateRealmDefault {
	if code <= 0 {
		code = 500
	}

	return &CreateRealmDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the create realm default response
func (o *CreateRealmDefault) WithStatusCode(code int) *CreateRealmDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the create realm default response
func (o *CreateRealmDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the create realm default response
func (o *CreateRealmDefault) WithPayload(payload *models.Problem) *CreateRealmDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create realm default response
func (o *CreateRealmDefault) SetPayload(payload *models.Problem) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateRealmDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
