// Code generated by go-swagger; DO NOT EDIT.

package realms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CreateRealmHandlerFunc turns a function with the right signature into a create realm handler
type CreateRealmHandlerFunc func(CreateRealmParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateRealmHandlerFunc) Handle(params CreateRealmParams) middleware.Responder {
	return fn(params)
}

// CreateRealmHandler interface for that can handle valid create realm params
type CreateRealmHandler interface {
	Handle(CreateRealmParams) middleware.Responder
}

// NewCreateRealm creates a new http.Handler for the create realm operation
func NewCreateRealm(ctx *middleware.Context, handler CreateRealmHandler) *CreateRealm {
	return &CreateRealm{Context: ctx, Handler: handler}
}

/* CreateRealm swagger:route POST /realms realms createRealm

Create new realm

*/
type CreateRealm struct {
	Context *middleware.Context
	Handler CreateRealmHandler
}

func (o *CreateRealm) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreateRealmParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
