// Code generated by go-swagger; DO NOT EDIT.

package realms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/grepplabs/tribe/api/v1/models"
)

// DeleteRealmOKCode is the HTTP code returned for type DeleteRealmOK
const DeleteRealmOKCode int = 200

/*DeleteRealmOK Successfully created.

swagger:response deleteRealmOK
*/
type DeleteRealmOK struct {
}

// NewDeleteRealmOK creates DeleteRealmOK with default headers values
func NewDeleteRealmOK() *DeleteRealmOK {

	return &DeleteRealmOK{}
}

// WriteResponse to the client
func (o *DeleteRealmOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteRealmBadRequestCode is the HTTP code returned for type DeleteRealmBadRequest
const DeleteRealmBadRequestCode int = 400

/*DeleteRealmBadRequest Invalid request body.

swagger:response deleteRealmBadRequest
*/
type DeleteRealmBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Problem `json:"body,omitempty"`
}

// NewDeleteRealmBadRequest creates DeleteRealmBadRequest with default headers values
func NewDeleteRealmBadRequest() *DeleteRealmBadRequest {

	return &DeleteRealmBadRequest{}
}

// WithPayload adds the payload to the delete realm bad request response
func (o *DeleteRealmBadRequest) WithPayload(payload *models.Problem) *DeleteRealmBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete realm bad request response
func (o *DeleteRealmBadRequest) SetPayload(payload *models.Problem) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteRealmBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteRealmUnauthorizedCode is the HTTP code returned for type DeleteRealmUnauthorized
const DeleteRealmUnauthorizedCode int = 401

/*DeleteRealmUnauthorized Invalid token.

swagger:response deleteRealmUnauthorized
*/
type DeleteRealmUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Problem `json:"body,omitempty"`
}

// NewDeleteRealmUnauthorized creates DeleteRealmUnauthorized with default headers values
func NewDeleteRealmUnauthorized() *DeleteRealmUnauthorized {

	return &DeleteRealmUnauthorized{}
}

// WithPayload adds the payload to the delete realm unauthorized response
func (o *DeleteRealmUnauthorized) WithPayload(payload *models.Problem) *DeleteRealmUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete realm unauthorized response
func (o *DeleteRealmUnauthorized) SetPayload(payload *models.Problem) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteRealmUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteRealmForbiddenCode is the HTTP code returned for type DeleteRealmForbidden
const DeleteRealmForbiddenCode int = 403

/*DeleteRealmForbidden Insufficient scope.

swagger:response deleteRealmForbidden
*/
type DeleteRealmForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Problem `json:"body,omitempty"`
}

// NewDeleteRealmForbidden creates DeleteRealmForbidden with default headers values
func NewDeleteRealmForbidden() *DeleteRealmForbidden {

	return &DeleteRealmForbidden{}
}

// WithPayload adds the payload to the delete realm forbidden response
func (o *DeleteRealmForbidden) WithPayload(payload *models.Problem) *DeleteRealmForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete realm forbidden response
func (o *DeleteRealmForbidden) SetPayload(payload *models.Problem) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteRealmForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteRealmNotFoundCode is the HTTP code returned for type DeleteRealmNotFound
const DeleteRealmNotFoundCode int = 404

/*DeleteRealmNotFound Not found.

swagger:response deleteRealmNotFound
*/
type DeleteRealmNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Problem `json:"body,omitempty"`
}

// NewDeleteRealmNotFound creates DeleteRealmNotFound with default headers values
func NewDeleteRealmNotFound() *DeleteRealmNotFound {

	return &DeleteRealmNotFound{}
}

// WithPayload adds the payload to the delete realm not found response
func (o *DeleteRealmNotFound) WithPayload(payload *models.Problem) *DeleteRealmNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete realm not found response
func (o *DeleteRealmNotFound) SetPayload(payload *models.Problem) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteRealmNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteRealmTooManyRequestsCode is the HTTP code returned for type DeleteRealmTooManyRequests
const DeleteRealmTooManyRequestsCode int = 429

/*DeleteRealmTooManyRequests Rate limiting

swagger:response deleteRealmTooManyRequests
*/
type DeleteRealmTooManyRequests struct {

	/*
	  In: Body
	*/
	Payload *models.Problem `json:"body,omitempty"`
}

// NewDeleteRealmTooManyRequests creates DeleteRealmTooManyRequests with default headers values
func NewDeleteRealmTooManyRequests() *DeleteRealmTooManyRequests {

	return &DeleteRealmTooManyRequests{}
}

// WithPayload adds the payload to the delete realm too many requests response
func (o *DeleteRealmTooManyRequests) WithPayload(payload *models.Problem) *DeleteRealmTooManyRequests {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete realm too many requests response
func (o *DeleteRealmTooManyRequests) SetPayload(payload *models.Problem) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteRealmTooManyRequests) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(429)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*DeleteRealmDefault Unexpected error

swagger:response deleteRealmDefault
*/
type DeleteRealmDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Problem `json:"body,omitempty"`
}

// NewDeleteRealmDefault creates DeleteRealmDefault with default headers values
func NewDeleteRealmDefault(code int) *DeleteRealmDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteRealmDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete realm default response
func (o *DeleteRealmDefault) WithStatusCode(code int) *DeleteRealmDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete realm default response
func (o *DeleteRealmDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete realm default response
func (o *DeleteRealmDefault) WithPayload(payload *models.Problem) *DeleteRealmDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete realm default response
func (o *DeleteRealmDefault) SetPayload(payload *models.Problem) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteRealmDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
