// Code generated by go-swagger; DO NOT EDIT.

package realms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteRealmHandlerFunc turns a function with the right signature into a delete realm handler
type DeleteRealmHandlerFunc func(DeleteRealmParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteRealmHandlerFunc) Handle(params DeleteRealmParams) middleware.Responder {
	return fn(params)
}

// DeleteRealmHandler interface for that can handle valid delete realm params
type DeleteRealmHandler interface {
	Handle(DeleteRealmParams) middleware.Responder
}

// NewDeleteRealm creates a new http.Handler for the delete realm operation
func NewDeleteRealm(ctx *middleware.Context, handler DeleteRealmHandler) *DeleteRealm {
	return &DeleteRealm{Context: ctx, Handler: handler}
}

/*DeleteRealm swagger:route DELETE /realms/{realm_id} realms deleteRealm

Delete realm

*/
type DeleteRealm struct {
	Context *middleware.Context
	Handler DeleteRealmHandler
}

func (o *DeleteRealm) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteRealmParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
