// Code generated by go-swagger; DO NOT EDIT.

package realms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetRealmHandlerFunc turns a function with the right signature into a get realm handler
type GetRealmHandlerFunc func(GetRealmParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetRealmHandlerFunc) Handle(params GetRealmParams) middleware.Responder {
	return fn(params)
}

// GetRealmHandler interface for that can handle valid get realm params
type GetRealmHandler interface {
	Handle(GetRealmParams) middleware.Responder
}

// NewGetRealm creates a new http.Handler for the get realm operation
func NewGetRealm(ctx *middleware.Context, handler GetRealmHandler) *GetRealm {
	return &GetRealm{Context: ctx, Handler: handler}
}

/*GetRealm swagger:route GET /realms/{realm_id} realms getRealm

Get realm

*/
type GetRealm struct {
	Context *middleware.Context
	Handler GetRealmHandler
}

func (o *GetRealm) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetRealmParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
