// Code generated by go-swagger; DO NOT EDIT.

package realms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/grepplabs/tribe/api/v1/models"
)

// GetRealmFoundRealmCode is the HTTP code returned for type GetRealmFoundRealm
const GetRealmFoundRealmCode int = 200

/*GetRealmFoundRealm found

swagger:response getRealmFoundRealm
*/
type GetRealmFoundRealm struct {

	/*
	  In: Body
	*/
	Payload *models.GetRealmResponse `json:"body,omitempty"`
}

// NewGetRealmFoundRealm creates GetRealmFoundRealm with default headers values
func NewGetRealmFoundRealm() *GetRealmFoundRealm {

	return &GetRealmFoundRealm{}
}

// WithPayload adds the payload to the get realm found realm response
func (o *GetRealmFoundRealm) WithPayload(payload *models.GetRealmResponse) *GetRealmFoundRealm {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get realm found realm response
func (o *GetRealmFoundRealm) SetPayload(payload *models.GetRealmResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRealmFoundRealm) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetRealmBadRequestCode is the HTTP code returned for type GetRealmBadRequest
const GetRealmBadRequestCode int = 400

/*GetRealmBadRequest Invalid request body.

swagger:response getRealmBadRequest
*/
type GetRealmBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Problem `json:"body,omitempty"`
}

// NewGetRealmBadRequest creates GetRealmBadRequest with default headers values
func NewGetRealmBadRequest() *GetRealmBadRequest {

	return &GetRealmBadRequest{}
}

// WithPayload adds the payload to the get realm bad request response
func (o *GetRealmBadRequest) WithPayload(payload *models.Problem) *GetRealmBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get realm bad request response
func (o *GetRealmBadRequest) SetPayload(payload *models.Problem) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRealmBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetRealmUnauthorizedCode is the HTTP code returned for type GetRealmUnauthorized
const GetRealmUnauthorizedCode int = 401

/*GetRealmUnauthorized Invalid token.

swagger:response getRealmUnauthorized
*/
type GetRealmUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Problem `json:"body,omitempty"`
}

// NewGetRealmUnauthorized creates GetRealmUnauthorized with default headers values
func NewGetRealmUnauthorized() *GetRealmUnauthorized {

	return &GetRealmUnauthorized{}
}

// WithPayload adds the payload to the get realm unauthorized response
func (o *GetRealmUnauthorized) WithPayload(payload *models.Problem) *GetRealmUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get realm unauthorized response
func (o *GetRealmUnauthorized) SetPayload(payload *models.Problem) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRealmUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetRealmForbiddenCode is the HTTP code returned for type GetRealmForbidden
const GetRealmForbiddenCode int = 403

/*GetRealmForbidden Insufficient scope.

swagger:response getRealmForbidden
*/
type GetRealmForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Problem `json:"body,omitempty"`
}

// NewGetRealmForbidden creates GetRealmForbidden with default headers values
func NewGetRealmForbidden() *GetRealmForbidden {

	return &GetRealmForbidden{}
}

// WithPayload adds the payload to the get realm forbidden response
func (o *GetRealmForbidden) WithPayload(payload *models.Problem) *GetRealmForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get realm forbidden response
func (o *GetRealmForbidden) SetPayload(payload *models.Problem) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRealmForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetRealmNotFoundCode is the HTTP code returned for type GetRealmNotFound
const GetRealmNotFoundCode int = 404

/*GetRealmNotFound Not found.

swagger:response getRealmNotFound
*/
type GetRealmNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Problem `json:"body,omitempty"`
}

// NewGetRealmNotFound creates GetRealmNotFound with default headers values
func NewGetRealmNotFound() *GetRealmNotFound {

	return &GetRealmNotFound{}
}

// WithPayload adds the payload to the get realm not found response
func (o *GetRealmNotFound) WithPayload(payload *models.Problem) *GetRealmNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get realm not found response
func (o *GetRealmNotFound) SetPayload(payload *models.Problem) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRealmNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetRealmTooManyRequestsCode is the HTTP code returned for type GetRealmTooManyRequests
const GetRealmTooManyRequestsCode int = 429

/*GetRealmTooManyRequests Rate limiting

swagger:response getRealmTooManyRequests
*/
type GetRealmTooManyRequests struct {

	/*
	  In: Body
	*/
	Payload *models.Problem `json:"body,omitempty"`
}

// NewGetRealmTooManyRequests creates GetRealmTooManyRequests with default headers values
func NewGetRealmTooManyRequests() *GetRealmTooManyRequests {

	return &GetRealmTooManyRequests{}
}

// WithPayload adds the payload to the get realm too many requests response
func (o *GetRealmTooManyRequests) WithPayload(payload *models.Problem) *GetRealmTooManyRequests {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get realm too many requests response
func (o *GetRealmTooManyRequests) SetPayload(payload *models.Problem) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRealmTooManyRequests) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(429)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetRealmDefault Unexpected error

swagger:response getRealmDefault
*/
type GetRealmDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Problem `json:"body,omitempty"`
}

// NewGetRealmDefault creates GetRealmDefault with default headers values
func NewGetRealmDefault(code int) *GetRealmDefault {
	if code <= 0 {
		code = 500
	}

	return &GetRealmDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get realm default response
func (o *GetRealmDefault) WithStatusCode(code int) *GetRealmDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get realm default response
func (o *GetRealmDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get realm default response
func (o *GetRealmDefault) WithPayload(payload *models.Problem) *GetRealmDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get realm default response
func (o *GetRealmDefault) SetPayload(payload *models.Problem) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRealmDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
