// Code generated by go-swagger; DO NOT EDIT.

package realms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/grepplabs/tribe/api/v1/models"
)

// ListRealmsHandlerFunc turns a function with the right signature into a list realms handler
type ListRealmsHandlerFunc func(ListRealmsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListRealmsHandlerFunc) Handle(params ListRealmsParams) middleware.Responder {
	return fn(params)
}

// ListRealmsHandler interface for that can handle valid list realms params
type ListRealmsHandler interface {
	Handle(ListRealmsParams) middleware.Responder
}

// NewListRealms creates a new http.Handler for the list realms operation
func NewListRealms(ctx *middleware.Context, handler ListRealmsHandler) *ListRealms {
	return &ListRealms{Context: ctx, Handler: handler}
}

/*ListRealms swagger:route GET /realms realms listRealms

List realms

*/
type ListRealms struct {
	Context *middleware.Context
	Handler ListRealmsHandler
}

func (o *ListRealms) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewListRealmsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// ListRealmsFoundRealmsBody list realms found realms body
//
// swagger:model ListRealmsFoundRealmsBody
type ListRealmsFoundRealmsBody struct {

	// links
	Links *models.Links `json:"_links,omitempty"`

	// results
	// Required: true
	Results []*models.GetRealmResponse `json:"results"`
}

// Validate validates this list realms found realms body
func (o *ListRealmsFoundRealmsBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateLinks(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateResults(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ListRealmsFoundRealmsBody) validateLinks(formats strfmt.Registry) error {

	if swag.IsZero(o.Links) { // not required
		return nil
	}

	if o.Links != nil {
		if err := o.Links.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("listRealmsFoundRealms" + "." + "_links")
			}
			return err
		}
	}

	return nil
}

func (o *ListRealmsFoundRealmsBody) validateResults(formats strfmt.Registry) error {

	if err := validate.Required("listRealmsFoundRealms"+"."+"results", "body", o.Results); err != nil {
		return err
	}

	for i := 0; i < len(o.Results); i++ {
		if swag.IsZero(o.Results[i]) { // not required
			continue
		}

		if o.Results[i] != nil {
			if err := o.Results[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("listRealmsFoundRealms" + "." + "results" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *ListRealmsFoundRealmsBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ListRealmsFoundRealmsBody) UnmarshalBinary(b []byte) error {
	var res ListRealmsFoundRealmsBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
