// Code generated by go-swagger; DO NOT EDIT.

package realms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/grepplabs/tribe/api/v1/models"
)

// ListRealmsFoundRealmsCode is the HTTP code returned for type ListRealmsFoundRealms
const ListRealmsFoundRealmsCode int = 200

/*ListRealmsFoundRealms found

swagger:response listRealmsFoundRealms
*/
type ListRealmsFoundRealms struct {

	/*
	  In: Body
	*/
	Payload *ListRealmsFoundRealmsBody `json:"body,omitempty"`
}

// NewListRealmsFoundRealms creates ListRealmsFoundRealms with default headers values
func NewListRealmsFoundRealms() *ListRealmsFoundRealms {

	return &ListRealmsFoundRealms{}
}

// WithPayload adds the payload to the list realms found realms response
func (o *ListRealmsFoundRealms) WithPayload(payload *ListRealmsFoundRealmsBody) *ListRealmsFoundRealms {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list realms found realms response
func (o *ListRealmsFoundRealms) SetPayload(payload *ListRealmsFoundRealmsBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListRealmsFoundRealms) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListRealmsBadRequestCode is the HTTP code returned for type ListRealmsBadRequest
const ListRealmsBadRequestCode int = 400

/*ListRealmsBadRequest Invalid request body.

swagger:response listRealmsBadRequest
*/
type ListRealmsBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Problem `json:"body,omitempty"`
}

// NewListRealmsBadRequest creates ListRealmsBadRequest with default headers values
func NewListRealmsBadRequest() *ListRealmsBadRequest {

	return &ListRealmsBadRequest{}
}

// WithPayload adds the payload to the list realms bad request response
func (o *ListRealmsBadRequest) WithPayload(payload *models.Problem) *ListRealmsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list realms bad request response
func (o *ListRealmsBadRequest) SetPayload(payload *models.Problem) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListRealmsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListRealmsUnauthorizedCode is the HTTP code returned for type ListRealmsUnauthorized
const ListRealmsUnauthorizedCode int = 401

/*ListRealmsUnauthorized Invalid token.

swagger:response listRealmsUnauthorized
*/
type ListRealmsUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Problem `json:"body,omitempty"`
}

// NewListRealmsUnauthorized creates ListRealmsUnauthorized with default headers values
func NewListRealmsUnauthorized() *ListRealmsUnauthorized {

	return &ListRealmsUnauthorized{}
}

// WithPayload adds the payload to the list realms unauthorized response
func (o *ListRealmsUnauthorized) WithPayload(payload *models.Problem) *ListRealmsUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list realms unauthorized response
func (o *ListRealmsUnauthorized) SetPayload(payload *models.Problem) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListRealmsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListRealmsForbiddenCode is the HTTP code returned for type ListRealmsForbidden
const ListRealmsForbiddenCode int = 403

/*ListRealmsForbidden Insufficient scope.

swagger:response listRealmsForbidden
*/
type ListRealmsForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Problem `json:"body,omitempty"`
}

// NewListRealmsForbidden creates ListRealmsForbidden with default headers values
func NewListRealmsForbidden() *ListRealmsForbidden {

	return &ListRealmsForbidden{}
}

// WithPayload adds the payload to the list realms forbidden response
func (o *ListRealmsForbidden) WithPayload(payload *models.Problem) *ListRealmsForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list realms forbidden response
func (o *ListRealmsForbidden) SetPayload(payload *models.Problem) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListRealmsForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListRealmsConflictCode is the HTTP code returned for type ListRealmsConflict
const ListRealmsConflictCode int = 409

/*ListRealmsConflict Already exists.

swagger:response listRealmsConflict
*/
type ListRealmsConflict struct {

	/*
	  In: Body
	*/
	Payload *models.Problem `json:"body,omitempty"`
}

// NewListRealmsConflict creates ListRealmsConflict with default headers values
func NewListRealmsConflict() *ListRealmsConflict {

	return &ListRealmsConflict{}
}

// WithPayload adds the payload to the list realms conflict response
func (o *ListRealmsConflict) WithPayload(payload *models.Problem) *ListRealmsConflict {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list realms conflict response
func (o *ListRealmsConflict) SetPayload(payload *models.Problem) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListRealmsConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(409)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListRealmsTooManyRequestsCode is the HTTP code returned for type ListRealmsTooManyRequests
const ListRealmsTooManyRequestsCode int = 429

/*ListRealmsTooManyRequests Rate limiting

swagger:response listRealmsTooManyRequests
*/
type ListRealmsTooManyRequests struct {

	/*
	  In: Body
	*/
	Payload *models.Problem `json:"body,omitempty"`
}

// NewListRealmsTooManyRequests creates ListRealmsTooManyRequests with default headers values
func NewListRealmsTooManyRequests() *ListRealmsTooManyRequests {

	return &ListRealmsTooManyRequests{}
}

// WithPayload adds the payload to the list realms too many requests response
func (o *ListRealmsTooManyRequests) WithPayload(payload *models.Problem) *ListRealmsTooManyRequests {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list realms too many requests response
func (o *ListRealmsTooManyRequests) SetPayload(payload *models.Problem) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListRealmsTooManyRequests) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(429)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*ListRealmsDefault Unexpected error

swagger:response listRealmsDefault
*/
type ListRealmsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Problem `json:"body,omitempty"`
}

// NewListRealmsDefault creates ListRealmsDefault with default headers values
func NewListRealmsDefault(code int) *ListRealmsDefault {
	if code <= 0 {
		code = 500
	}

	return &ListRealmsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the list realms default response
func (o *ListRealmsDefault) WithStatusCode(code int) *ListRealmsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the list realms default response
func (o *ListRealmsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the list realms default response
func (o *ListRealmsDefault) WithPayload(payload *models.Problem) *ListRealmsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list realms default response
func (o *ListRealmsDefault) SetPayload(payload *models.Problem) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListRealmsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
