// Code generated by go-swagger; DO NOT EDIT.

package realms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/grepplabs/tribe/api/v1/models"
)

// UpdateRealmOKCode is the HTTP code returned for type UpdateRealmOK
const UpdateRealmOKCode int = 200

/*UpdateRealmOK Successfully created.

swagger:response updateRealmOK
*/
type UpdateRealmOK struct {
}

// NewUpdateRealmOK creates UpdateRealmOK with default headers values
func NewUpdateRealmOK() *UpdateRealmOK {

	return &UpdateRealmOK{}
}

// WriteResponse to the client
func (o *UpdateRealmOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// UpdateRealmBadRequestCode is the HTTP code returned for type UpdateRealmBadRequest
const UpdateRealmBadRequestCode int = 400

/*UpdateRealmBadRequest Invalid request body.

swagger:response updateRealmBadRequest
*/
type UpdateRealmBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Problem `json:"body,omitempty"`
}

// NewUpdateRealmBadRequest creates UpdateRealmBadRequest with default headers values
func NewUpdateRealmBadRequest() *UpdateRealmBadRequest {

	return &UpdateRealmBadRequest{}
}

// WithPayload adds the payload to the update realm bad request response
func (o *UpdateRealmBadRequest) WithPayload(payload *models.Problem) *UpdateRealmBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update realm bad request response
func (o *UpdateRealmBadRequest) SetPayload(payload *models.Problem) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateRealmBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateRealmUnauthorizedCode is the HTTP code returned for type UpdateRealmUnauthorized
const UpdateRealmUnauthorizedCode int = 401

/*UpdateRealmUnauthorized Invalid token.

swagger:response updateRealmUnauthorized
*/
type UpdateRealmUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Problem `json:"body,omitempty"`
}

// NewUpdateRealmUnauthorized creates UpdateRealmUnauthorized with default headers values
func NewUpdateRealmUnauthorized() *UpdateRealmUnauthorized {

	return &UpdateRealmUnauthorized{}
}

// WithPayload adds the payload to the update realm unauthorized response
func (o *UpdateRealmUnauthorized) WithPayload(payload *models.Problem) *UpdateRealmUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update realm unauthorized response
func (o *UpdateRealmUnauthorized) SetPayload(payload *models.Problem) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateRealmUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateRealmForbiddenCode is the HTTP code returned for type UpdateRealmForbidden
const UpdateRealmForbiddenCode int = 403

/*UpdateRealmForbidden Insufficient scope.

swagger:response updateRealmForbidden
*/
type UpdateRealmForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Problem `json:"body,omitempty"`
}

// NewUpdateRealmForbidden creates UpdateRealmForbidden with default headers values
func NewUpdateRealmForbidden() *UpdateRealmForbidden {

	return &UpdateRealmForbidden{}
}

// WithPayload adds the payload to the update realm forbidden response
func (o *UpdateRealmForbidden) WithPayload(payload *models.Problem) *UpdateRealmForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update realm forbidden response
func (o *UpdateRealmForbidden) SetPayload(payload *models.Problem) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateRealmForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateRealmNotFoundCode is the HTTP code returned for type UpdateRealmNotFound
const UpdateRealmNotFoundCode int = 404

/*UpdateRealmNotFound Not found.

swagger:response updateRealmNotFound
*/
type UpdateRealmNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Problem `json:"body,omitempty"`
}

// NewUpdateRealmNotFound creates UpdateRealmNotFound with default headers values
func NewUpdateRealmNotFound() *UpdateRealmNotFound {

	return &UpdateRealmNotFound{}
}

// WithPayload adds the payload to the update realm not found response
func (o *UpdateRealmNotFound) WithPayload(payload *models.Problem) *UpdateRealmNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update realm not found response
func (o *UpdateRealmNotFound) SetPayload(payload *models.Problem) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateRealmNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateRealmTooManyRequestsCode is the HTTP code returned for type UpdateRealmTooManyRequests
const UpdateRealmTooManyRequestsCode int = 429

/*UpdateRealmTooManyRequests Rate limiting

swagger:response updateRealmTooManyRequests
*/
type UpdateRealmTooManyRequests struct {

	/*
	  In: Body
	*/
	Payload *models.Problem `json:"body,omitempty"`
}

// NewUpdateRealmTooManyRequests creates UpdateRealmTooManyRequests with default headers values
func NewUpdateRealmTooManyRequests() *UpdateRealmTooManyRequests {

	return &UpdateRealmTooManyRequests{}
}

// WithPayload adds the payload to the update realm too many requests response
func (o *UpdateRealmTooManyRequests) WithPayload(payload *models.Problem) *UpdateRealmTooManyRequests {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update realm too many requests response
func (o *UpdateRealmTooManyRequests) SetPayload(payload *models.Problem) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateRealmTooManyRequests) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(429)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*UpdateRealmDefault Unexpected error

swagger:response updateRealmDefault
*/
type UpdateRealmDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Problem `json:"body,omitempty"`
}

// NewUpdateRealmDefault creates UpdateRealmDefault with default headers values
func NewUpdateRealmDefault(code int) *UpdateRealmDefault {
	if code <= 0 {
		code = 500
	}

	return &UpdateRealmDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the update realm default response
func (o *UpdateRealmDefault) WithStatusCode(code int) *UpdateRealmDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the update realm default response
func (o *UpdateRealmDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the update realm default response
func (o *UpdateRealmDefault) WithPayload(payload *models.Problem) *UpdateRealmDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update realm default response
func (o *UpdateRealmDefault) SetPayload(payload *models.Problem) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateRealmDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
