// Code generated by go-swagger; DO NOT EDIT.

package realms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"

	"github.com/grepplabs/tribe/api/v1/models"
)

// NewUpdateRealmParams creates a new UpdateRealmParams object
// no default values defined in spec.
func NewUpdateRealmParams() UpdateRealmParams {

	return UpdateRealmParams{}
}

// UpdateRealmParams contains all the bound params for the update realm operation
// typically these are obtained from a http.Request
//
// swagger:parameters update-realm
type UpdateRealmParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: body
	*/
	Realm *models.UpdateRealmRequest
	/*Realm id.
	  Required: true
	  In: path
	*/
	RealmID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewUpdateRealmParams() beforehand.
func (o *UpdateRealmParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.UpdateRealmRequest
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("realm", "body", ""))
			} else {
				res = append(res, errors.NewParseError("realm", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Realm = &body
			}
		}
	} else {
		res = append(res, errors.Required("realm", "body", ""))
	}
	rRealmID, rhkRealmID, _ := route.Params.GetOK("realm_id")
	if err := o.bindRealmID(rRealmID, rhkRealmID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindRealmID binds and validates parameter RealmID from path.
func (o *UpdateRealmParams) bindRealmID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.RealmID = raw

	return nil
}
