// Code generated by go-swagger; DO NOT EDIT.

package healthz

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/grepplabs/tribe/api/v1/models"
)

// GetHealthyOKCode is the HTTP code returned for type GetHealthyOK
const GetHealthyOKCode int = 200

/*GetHealthyOK Success

swagger:response getHealthyOK
*/
type GetHealthyOK struct {
}

// NewGetHealthyOK creates GetHealthyOK with default headers values
func NewGetHealthyOK() *GetHealthyOK {

	return &GetHealthyOK{}
}

// WriteResponse to the client
func (o *GetHealthyOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// GetHealthyServiceUnavailableCode is the HTTP code returned for type GetHealthyServiceUnavailable
const GetHealthyServiceUnavailableCode int = 503

/*GetHealthyServiceUnavailable Service Unavailable

swagger:response getHealthyServiceUnavailable
*/
type GetHealthyServiceUnavailable struct {

	/*
	  In: Body
	*/
	Payload *models.Problem `json:"body,omitempty"`
}

// NewGetHealthyServiceUnavailable creates GetHealthyServiceUnavailable with default headers values
func NewGetHealthyServiceUnavailable() *GetHealthyServiceUnavailable {

	return &GetHealthyServiceUnavailable{}
}

// WithPayload adds the payload to the get healthy service unavailable response
func (o *GetHealthyServiceUnavailable) WithPayload(payload *models.Problem) *GetHealthyServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get healthy service unavailable response
func (o *GetHealthyServiceUnavailable) SetPayload(payload *models.Problem) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetHealthyServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
