// Code generated by go-swagger; DO NOT EDIT.

package healthz

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/grepplabs/tribe/api/v1/models"
)

// GetReadyOKCode is the HTTP code returned for type GetReadyOK
const GetReadyOKCode int = 200

/*GetReadyOK Success

swagger:response getReadyOK
*/
type GetReadyOK struct {
}

// NewGetReadyOK creates GetReadyOK with default headers values
func NewGetReadyOK() *GetReadyOK {

	return &GetReadyOK{}
}

// WriteResponse to the client
func (o *GetReadyOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// GetReadyServiceUnavailableCode is the HTTP code returned for type GetReadyServiceUnavailable
const GetReadyServiceUnavailableCode int = 503

/*GetReadyServiceUnavailable Service Unavailable

swagger:response getReadyServiceUnavailable
*/
type GetReadyServiceUnavailable struct {

	/*
	  In: Body
	*/
	Payload *models.Problem `json:"body,omitempty"`
}

// NewGetReadyServiceUnavailable creates GetReadyServiceUnavailable with default headers values
func NewGetReadyServiceUnavailable() *GetReadyServiceUnavailable {

	return &GetReadyServiceUnavailable{}
}

// WithPayload adds the payload to the get ready service unavailable response
func (o *GetReadyServiceUnavailable) WithPayload(payload *models.Problem) *GetReadyServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get ready service unavailable response
func (o *GetReadyServiceUnavailable) SetPayload(payload *models.Problem) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetReadyServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
